server:
  port: 8803

spring:
  application:
    name: cloud-stream-consumer8803
  rabbitmq:
    host: 47.98.113.118
    port: 5672
    username: admin
    password: youis218945
  cloud:
    stream:
      bindings: # 服务的整合处理
        input: # 这个名字是一个通道的名称
          destination: studyExchange # 表示要使用的Exchange名称定义
          content-type: application/json # 设置消息类型，本次为json，文本则为 text/plain
          group: donggege

eureka:
  instance:
    instance-id: cloud-stream-consumer8803
    prefer-ip-address: true   # 访问路径可以显示ip地址
  client:
    # 表示将自己注册到注册中心
    register-with-eureka: true
    # 是否从eureka-server中抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true，才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      # defaultZone: http://localhost:7001/eureka   # 单机版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka    # 集群版
