server:
  port: 3344

spring:
  application:
    name: cloud-config-center3344
  cloud:
    config:
      server:
        git:
#          uri: git@github.com:suiweidong/SpringCloud-Config.git   配置会有问题，未知道原因
          uri: https://github.com/suiweidong/SpringCloud-Config.git
          # 搜索目录
          search-paths:
            - springcloud-config
      # 读取分支
      profile: dev      # profile对应config server所获取的配置文件中的{profile}
      label: master     # 指定Git仓库的分支，对应config server所获取的配置文件的{label}
  rabbitmq:  # rabbitmq相关配置
    host: 47.98.113.118
    port: 5672
    username: admin
    password: youis218945

# rabbitmq相关配置，暴露bus刷新配置的端点
management:
  endpoints: # 暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'

eureka:
  instance:
    instance-id: cloud-config-center
    prefer-ip-address: true   # 访问路径可以显示ip地址
  client:
    # 表示将自己注册到注册中心
    register-with-eureka: true
    # 是否从eureka-server中抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true，才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      # defaultZone: http://localhost:7001/eureka   # 单机版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka    # 集群版