server:
  port: 9527

spring:
  application:
    name: cloud-gateway-gateway9527
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_getPaymentById            # 路由的ID，没有固定规则但要求唯一，建议配合服务名
          #          uri:  http://localhost:8001           # 匹配后，提供服务的路由地址
          uri: lb://cloud-provider-service
          predicates:
            - Path=/cloud/payment/get/**      # 断言，路径相配置的进行路由    注意  “path” 与 “=”  之间  、 “=” 与 “/” 之间不要有空格
        - id: payment_lb
          #          uri: http://localhost:8001
          uri: lb://cloud-provider-service    # 匹配后提供服务的路由地址   lb 为load balance 的缩写
#          filters:
#            - AddRequestParameter=X-Request-Id,1024  #过滤工厂会在匹配的请求头上加一对请求头，名称为X-Request-Id值为1024
          predicates:
            - Path=/cloud/payment/lb/**
#            - After=2020-10-18T00:57:07.286+08:00[Asia/Shanghai]
#            - Before=2020-10-18T00:57:07.286+08:00[Asia/Shanghai]
#            - Between=2020-10-18T00:57:07.286+08:00[Asia/Shanghai],2020-11-18T00:57:07.286+08:00[Asia/Shanghai]
#            - Cookie=suiweidong,aabb
#            - Header=X-Request-Id, \d+   #请求头中要有X-Request-Id属性并且值为整数的正则表达式
#            - Host=**.suiweidong.com,**.xiaohonghong.com
#            - Method=Get
#            - Query=username,\d+  # 要有参数名，而且参数名username值还要是整数才能路由

eureka:
  instance:
    instance-id: dateway9527
    prefer-ip-address: true  # 访问路径可以显示ip地址
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒(默认是30秒)
    #lease-renewal-interval-in-seconds: 1
    #Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒(默认是90秒)，超时将剔除服务
    #lease-expiration-duration-in-seconds: 2
  client:
    # 表示将自己注册到注册中心
    register-with-eureka: true
    # 是否从eureka-server中抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true，才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      # defaultZone: http://localhost:7001/eureka   # 单机版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka     # 集群版
