server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com   #s Eureka服务端实例名称
  client:
    # false 表示不向注册中心注册自己
    register-with-eureka: false
    # false 表示自己就是注册中心，职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      # 设置Eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      # defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka    # 单机版
      defaultZone: http://eureka7002.com:7002/eureka, http://eureka7003.com:7003/eureka    #集群版
    #server:
    #关闭自我保护机制，保证不可用服务被及时踢除
    #enable-self-preservation: false
    #eviction-interval-timer-in-ms: 2000